name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        shell: bash
        working-directory: client-side\tools-catalogue
      - run: npm run build --if--present
        shell: bash
        working-directory: client-side\tools-catalogue
      # Add additional build steps here
      # - run: ...
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: "/Tools-angular-project"
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live
          projectId: tools-co
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

